{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Project Cost",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT department, total_cost, currency FROM public_public.project_cost ORDER BY total_cost DESC "
    }
   ]
  },
  {
   "title": "Top 10 Issue Distribution",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT issue_type, SUM(issue_count) FROM public_public.issue_distribution GROUP BY issue_type ORDER BY SUM(issue_count) DESC LIMIT 10 "
    }
   ]
  },
  {
   "title": "Activity On Different Repositories.",
   "type": "barchart",
   "gridPos": { "h": 35, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT repository_name, commit_count, issue_count, pr_count FROM public_public.repository_activity "
    }
   ]
  }
 ]
}